name: webfeed
version: 0.8.0
description: webfeed is a dart package for parsing RSS and Atom feeds. Media, DublinCore, iTunes, Syndication namespaces are also supported.
homepage: https://github.com/witochandra/webfeed
environment:
  sdk: '>=3.0.0'
dependencies:
  xml: "^6.2.0"
  intl: "^0.18.1"
dev_dependencies:
  test: ^1.3.0
  http: "^0.13.0"
